# Generated by Django 3.0.3 on 2020-02-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalLibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBookCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readStatus', models.CharField(blank=True, max_length=200, null=True)),
                ('myRating', models.PositiveIntegerField(default=5, null=True)),
                ('myReview', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalLibrary.Book')),
            ],
        ),
    ]
